### ISSUE TITLE
What Is My Browser Shows CEF 59 not 84

### ISSUE THREAD

**Issue by ffreality** [shiniu0606/ChromiumUI#1]
I extracted Source/ThirdParty/ChromiumUILibrary.7z and re-compiled the plugin.
I created a blueprint class based on ChromiumUI C++ Classes / ChromiumUI/Public/WebBrowser and used it in a widget
After begin play it asks me to alllow CEFSubProcess and I allowed it.

but https://www.whatismybrowser.com/ shows me that I use Chromium 59 not 84

I use 4.27.2 Epic Client version.
My project is a C++ project
Native WebBrowser and Proxy plugins disabled.

**Comment by shiniu0606** [comment]
the ProductVersion not update. 
I have fixed.Please update the code

**Comment by shiniu0606** [comment]
You can check the details with url "chrome://version/"

**Comment by ffreality** [comment]
Thank you very much it works perfectly !
