### ISSUE TITLE
播放视频的支持

### ISSUE THREAD

**Issue by pscxtc** [shiniu0606/ChromiumUI#10]
大佬 有考虑过增加 播放视频的支持么,我看网上主要是对 H.264 的支持, 这样就可以在h5中 使用 video 标签,很多功能就灵活起来了
我使用 http://html5test.com/ 网站测试了当前集成的浏览器,确实不支持 视频的 H.264

**Comment by shiniu0606** [comment]
编译cef比较费劲，免费版本应该不会做了。ue4商店有收费版本的插件实现了该功能. https://www.unrealengine.com/marketplace/en-US/product/dbbrowser

**Comment by pscxtc** [comment]
好的,谢谢
