### ISSUE TITLE
Not Able to open in UE4.27

### ISSUE THREAD

**Issue by avokhour** [shiniu0606/ChromiumUI#11]
Hello there,

I am trying to work with the chromium 84 in order to open a web appliction inside ue4.
I am trying to install the plug in on UE4.27.2 but having problems with it.
First I extracted the entire file.
Then extracted the ChromiumUILibrary.7z in the same folder.
Then the entire folder copied it to the project and created a plugin folder and placed them over there.
I am getting an error:

The following modules are missing or build with a different engine verions:
ChromiumUI
Would  you like to rebuild them now?

I pressed Yes

Project_Name  could not be compiled. Try rebuilding from source manually.

I am not able to open the project.
How can I fix this problem and can I want to open web application .
Your urgent reply would be highly appricated.

**Comment by avokhour** [comment]
I also changed the name of the folder to ChromiumUI instead of ChromiumUI-main

**Comment by shiniu0606** [comment]
sorry，you need create project with c++,not blueprint. this plugin can not compile in blueprint project

**Comment by avokhour** [comment]
Dear Shiniu,

I have opened a new C++ project.
I extracted the ChromiumUI Folder to the desktop.
Then extracted the folder ChromiumUI\Source\ThirdParty\ChromiumUILibrary in
the same folder.
Then copied the entire ChromuiumUI-main folder.
Opened a new folder in the project folder called Plugins.
Then pasted the entire ChromuimUI-main inside it.
Changed the name to ChromiumUI and removed the -main.
Opened the visual studio to build the project and debug it.
It says the chromiumUI is missing some features or build with older
versions.
I am not able to open it.
Can you share with me a project with the chromium 84 inside it to try it
out.
Your help is much appreciated.

Warm Regards,






*[CONFIDENTIALITY AND PRIVACY NOTICE]* Information transmitted by this
email is proprietary to *AVINOX* & *GABIG* and is intended for use only by
the individual or entity to which it is addressed, and may contain
information that is private, privileged, confidential or exempt from
disclosure under applicable law. If you are not the intended recipient or
it appears that this mail has been forwarded to you without proper
authority, you are notified that any use or dissemination of this
information in any manner is strictly prohibited. In such cases, please
delete this mail from your records.

**Comment by avokhour** [comment]
I am trying to launch it from VS but getting these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to instantiate module 'ChromiumUILibrary': System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\Documents\Unreal Projects\CPPCode\Plugins\ChromiumUI\Source\ThirdParty\ChromiumUILibrary\Binaries'.	CPPCode	C:\Users\Admin\Documents\Unreal Projects\CPPCode\Intermediate\ProjectFiles\UnrealBuildTool	1	


Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Program Files\Epic Games\UE_4.27\Engine\Build\BatchFiles\Build.bat" CPPCodeEditor Win64 Development -Project="C:\Users\Admin\Documents\Unreal Projects\CPPCode\CPPCode.uproject" -WaitMutex -FromMsBuild" exited with code 6.	CPPCode	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	45

**Comment by avokhour** [comment]
Do you have a ready project that I can test on.
Also can you send us a tutorial on how to install the plugin.

**Comment by shiniu0606** [comment]
https://drive.google.com/file/d/1NX5tia_TmoSa-vpjKoErWU8EbiE2P4pK/view?usp=sharing
this project can test

**Comment by avokhour** [comment]
Thank you very much.
You have been very very helpful.
Are you thinking of even updating to the newer version?
If yes, let me know, we can help you with it.

**Comment by shiniu0606** [comment]
yes i thought about it, but compile cef is very hard in china,I haven't compiled successfully yet
