### ISSUE TITLE
Duplicate leaf header name found issue

### ISSUE THREAD

**Issue by ffreality** [shiniu0606/ChromiumUI#2]
Hello again,
when I want to package project it gives me "Duplicate leaf header name found: ChromiumUI/Source/ChromiumUI/Public/WebJSFunction.h(1) Look at original: Original WebJSFunction.h in engine" error.

I checked both WebJSFunction.h headers.
The original one used WEBBROWSER_API as a dll import export define and FWebJSParam as structure.
Yours used CHROMIUMUI_API as structure and FWebJSParam as a CHROMIUMUI_API type variable.

**Comment by shiniu0606** [comment]
I test packaged project was successful. should check if the  Web Browser plugin is removed in uproject file.

**Comment by shiniu0606** [comment]
this error is duplication files in porject.maybe you need to clean project temp folder and Generate Visual Studio project again

**Comment by ffreality** [comment]
WebBrowser and Proxy disabled but I will give a try to delete entries from uproject and cleaning saved + intermediate folders

**Comment by ffreality** [comment]
I created a new CPP project and you can see active plugins in bellow. Error continues.
I use Visual Studio 2022

.project file active plugins

{
	"FileVersion": 3,
	"EngineAssociation": "4.27",
	"Category": "",
	"Description": "",
	"Modules": [
		{
			"Name": "FF_Plugins",
			"Type": "Runtime",
			"LoadingPhase": "Default"
		}
	],
	"Plugins": [
		{
			"Name": "OculusOpenXR",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win32",
				"Win64",
				"Android"
			]
		},
		{
			"Name": "OpenXRHandTracking",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Win32",
				"Win64",
				"Linux",
				"HoloLens",
				"Android"
			]
		},
		{
			"Name": "OpenXREyeTracker",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Win32",
				"Win64",
				"Linux",
				"HoloLens",
				"Android"
			]
		},
		{
			"Name": "SteamVR",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Win32",
				"Win64",
				"Linux"
			]
		},
		{
			"Name": "LidarPointCloud",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win64",
				"Mac",
				"Linux"
			]
		},
		{
			"Name": "Volumetrics",
			"Enabled": true
		},
		{
			"Name": "XCodeSourceCodeAccess",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Mac"
			]
		},
		{
			"Name": "VisualStudioCodeSourceCodeAccess",
			"Enabled": false
		},
		{
			"Name": "RiderSourceCodeAccess",
			"Enabled": false
		},
		{
			"Name": "NullSourceCodeAccess",
			"Enabled": false
		},
		{
			"Name": "KDevelopSourceCodeAccess",
			"Enabled": false
		},
		{
			"Name": "CodeLiteSourceCodeAccess",
			"Enabled": false
		},
		{
			"Name": "CodeView",
			"Enabled": true
		},
		{
			"Name": "CLionSourceCodeAccess",
			"Enabled": false
		},
		{
			"Name": "AnimationBudgetAllocator",
			"Enabled": true
		},
		{
			"Name": "ApexDestruction",
			"Enabled": true
		},
		{
			"Name": "ChaosCaching",
			"Enabled": true
		},
		{
			"Name": "ChaosVehiclesPlugin",
			"Enabled": true
		},
		{
			"Name": "ShallowWater",
			"Enabled": true
		},
		{
			"Name": "Reflex",
			"Enabled": true
		},
		{
			"Name": "PerformanceMonitor",
			"Enabled": true
		},
		{
			"Name": "DatasmithRuntime",
			"Enabled": true
		},
		{
			"Name": "OnlineSubsystemOculus",
			"Enabled": true
		},
		{
			"Name": "OnlineSubsystemIOS",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"IOS",
				"TVOS"
			]
		},
		{
			"Name": "OnlineSubsystemGooglePlay",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Android"
			]
		},
		{
			"Name": "OnlineFramework",
			"Enabled": true
		},
		{
			"Name": "GoogleCloudMessaging",
			"Enabled": false
		},
		{
			"Name": "WindowsMoviePlayer",
			"Enabled": false
		},
		{
			"Name": "AppleMoviePlayer",
			"Enabled": false
		},
		{
			"Name": "AndroidMoviePlayer",
			"Enabled": false
		},
		{
			"Name": "MobilePatchingUtils",
			"Enabled": false
		},
		{
			"Name": "MobileLauncherProfileWizard",
			"Enabled": false
		},
		{
			"Name": "MacGraphicsSwitching",
			"Enabled": false
		},
		{
			"Name": "DataCharts",
			"Enabled": true
		},
		{
			"Name": "AndroidMedia",
			"Enabled": false
		},
		{
			"Name": "BinkMedia",
			"Enabled": true
		},
		{
			"Name": "ElectraPlayer",
			"Enabled": true
		},
		{
			"Name": "ElectraCDM",
			"Enabled": true
		},
		{
			"Name": "ElectraUtil",
			"Enabled": true
		},
		{
			"Name": "MagicLeapMedia",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Lumin"
			]
		},
		{
			"Name": "WmfMedia",
			"Enabled": false
		},
		{
			"Name": "MediaIOFramework",
			"Enabled": true
		},
		{
			"Name": "MediaFrameworkUtilities",
			"Enabled": true
		},
		{
			"Name": "MagicLeap",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Lumin",
				"Mac",
				"Win64"
			]
		},
		{
			"Name": "LuminPlatformFeatures",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Lumin"
			]
		},
		{
			"Name": "MLSDK",
			"Enabled": false
		},
		{
			"Name": "USDImporter",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win64",
				"Mac",
				"Linux"
			]
		},
		{
			"Name": "MDLImporter",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win64",
				"Mac",
				"Linux"
			]
		},
		{
			"Name": "GLTFImporter",
			"Enabled": true
		},
		{
			"Name": "DatasmithImporter",
			"Enabled": true
		},
		{
			"Name": "DatasmithIFCImporter",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win64"
			]
		},
		{
			"Name": "DatasmithGLTFImporter",
			"Enabled": true
		},
		{
			"Name": "DatasmithFBXImporter",
			"Enabled": true
		},
		{
			"Name": "DatasmithCADImporter",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win64"
			]
		},
		{
			"Name": "DatasmithC4DImporter",
			"Enabled": true,
			"SupportedTargetPlatforms": [
				"Win64",
				"Mac"
			]
		},
		{
			"Name": "WindowsDeviceProfileSelector",
			"Enabled": true
		},
		{
			"Name": "LinuxDeviceProfileSelector",
			"Enabled": false
		},
		{
			"Name": "IOSDeviceProfileSelector",
			"Enabled": false
		},
		{
			"Name": "AndroidDeviceProfileSelector",
			"Enabled": false
		},
		{
			"Name": "DataprepGeometryOperations",
			"Enabled": true
		},
		{
			"Name": "DataprepEditor",
			"Enabled": true
		},
		{
			"Name": "BlueprintMaterialTextureNodes",
			"Enabled": true
		},
		{
			"Name": "BlueprintStats",
			"Enabled": true
		},
		{
			"Name": "BlueprintFileUtils",
			"Enabled": true
		},
		{
			"Name": "LocationServicesBPLibrary",
			"Enabled": false
		},
		{
			"Name": "MagicLeapPassableWorld",
			"Enabled": false,
			"SupportedTargetPlatforms": [
				"Lumin",
				"Mac",
				"Win64"
			]
		},
		{
			"Name": "OculusAudio",
			"Enabled": true
		},
		{
			"Name": "SoundVisualizations",
			"Enabled": true
		},
		{
			"Name": "SoundUtilities",
			"Enabled": true
		},
		{
			"Name": "GizmoFramework",
			"Enabled": true
		},
		{
			"Name": "GizmoEdMode",
			"Enabled": true
		},
		{
			"Name": "GooglePAD",
			"Enabled": false
		},
		{
			"Name": "AndroidPermission",
			"Enabled": false
		},
		{
			"Name": "PTMTool",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/946185f2400d4be9b8d4190e95df86c8"
		},
		{
			"Name": "ZipIt",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/product/6b6ffe9b7fd34e24a3529cde6903e581"
		},
		{
			"Name": "UniversalVoiceChatPro",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/product/eda7d893311147d1b7a6e8084be096c4"
		},
		{
			"Name": "ThermodynamicChart",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/abde3d8754e5448e90cddc53c915ebf1"
		},
		{
			"Name": "LowEntryEncryption",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/93647fb26bd14898b7ea63d4eefbf33a"
		},
		{
			"Name": "LowEntryExtStdLib",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/846c2ad08f164f45b0335ecebf85361e"
		},
		{
			"Name": "LowEntryFileManager",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/58edabbac7514311a4670c5d47a6fae6"
		},
		{
			"Name": "LowEntryHttpRequest",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/29d22bc9b02148d6bf6f57e1a0f660cc"
		},
		{
			"Name": "LowEntryJson",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/c108b5a8917c4c86873edf835237beab"
		},
		{
			"Name": "VFCreator",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/product/5973943aa2424ea0a722be0720642e5e"
		},
		{
			"Name": "PivotTool",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/a220ab040cb844beb355b0f159eabefa"
		},
		{
			"Name": "CleanProject",
			"Enabled": true,
			"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/13d45e838b954d67b9d5d01fa82635d9"
		}
	]
}

![image](https://user-images.githubusercontent.com/10528447/155198735-a767581e-a9de-4b4d-8982-7975e4f4df6b.png)

**Comment by shiniu0606** [comment]
OnlineFramework has WebBrowser plugin。

**Comment by clime57** [comment]
一样，然后我把原来的WebBrowser代码移走，报这样的错误
UATHelper: Packaging (Android (ASTC)):   ERROR: Could not find definition for module 'WebBrowser', (referenced via Target -> ChromiumUI.Build.cs -> WebBrowserTexture.Build.cs)
PackagingResults: Error: Could not find definition for module 'WebBrowser', (referenced via Target -> ChromiumUI.Build.cs -> WebBrowserTexture.Build.cs)

WebBrowserTexture这个模块使用了WebBrowser

**Comment by clime57** [comment]
一样，然后我把原来的WebBrowser代码移走，报这样的错误
UATHelper: Packaging (Android (ASTC)):   ERROR: Could not find definition for module 'WebBrowser', (referenced via Target -> ChromiumUI.Build.cs -> WebBrowserTexture.Build.cs)
PackagingResults: Error: Could not find definition for module 'WebBrowser', (referenced via Target -> ChromiumUI.Build.cs -> WebBrowserTexture.Build.cs)

WebBrowserTexture这个模块使用了WebBrowser

**Comment by shiniu0606** [comment]
抱歉，这个插件目前只处理了windows的支持。
