### ISSUE TITLE
您好，请问可以兼容webui吗

### ISSUE THREAD

**Issue by xs818818** [shiniu0606/ChromiumUI#4]
请问我想让webui直接调用您的代码，需要怎么修改

**Comment by shiniu0606** [comment]
可能需要修改webui，主体部分替换WebBrowser插件应用ChromiumUI应该就可以，主要是WebBrowserTexture相关的逻辑需要改动，这一块主要是编辑器相关的，应该也可以移除。webui相关功能，除开鼠标点击穿透的处理，其他部分ChromiumUI应该都有对应的函数的

**Comment by shiniu0606** [comment]
可以考虑用ChromiumUI替代webui使用，这边应该基本实现了webui相关处理，js和ue4的相互调用，鼠标点击穿透相关的支持已经增加。相关的demo在插件Content目录

**Comment by xs818818** [comment]
谢谢
