### ISSUE TITLE
尝试最新版本VS编译报错

### ISSUE THREAD

**Issue by xs818818** [shiniu0606/ChromiumUI#5]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Could not find definition for module 'ChromiumUILibrary', (referenced via Target -> ChromiumUI.Build.cs)	web	E:\projects\web\Intermediate\ProjectFiles\UnrealBuildTool	1	
Plugins\ChromiumUI\Source\ThirdParty\ChromiumUILibrary\Binaries
我已经解压缩了
我是4.27.2版本

**Comment by shiniu0606** [comment]
需要解压缩ChromiumUILibrary.7z

**Comment by xs818818** [comment]
我已经解压了，存放路径是这样的
E:\projects\web\Plugins\ChromiumUI\Source\ThirdParty\ChromiumUILibrary\Binaries

**Comment by xs818818** [comment]
抱歉，刚才查了，误把CS也和压缩包删了
